"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Binary-like Encryptor.py']
DATA_FILES = ['encryptor.py']
OPTIONS = {'argv_emulation': True,
           "plist" : {"CFBundleShortVersionString" : "0.1.4"}}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
